version: "3"

services:
  php:
     build: ./php
     env_file:
        - ./docker-compose-lesson.env
     environment:
        - MYSQL_HOST=mysql
     volumes:
       - ./php/public_html:/var/www/html
       - ./php/php:/var/www/php
       - ./php/vendor:/var/www/vendor
     ports:
        - 8001:80
  mysql:
    build: ./mysql
    env_file:
       - ./docker-compose-lesson.env
    ports:
       - 33006:3306